window.ST_PARAMS = {
  "subdomain":"dgtek",
  "testConfiguration":{
    "testConfigurationId":80649,
    "subscriptionId":1750001,
    "subdomain":"dgtek",
    "createdDate":"2020-01-13T08:30:00.000Z",
    "modifiedDate":"2020-01-13T08:30:00.000Z",
    "allowedServers":0,
    "serverNetwork":"speedtest",
    "dataProtectionContactId":0,
    "resellerContactId":0,
    "autoStart":false,
    "clientIcon":"desktop",
    "customerServers":[],
    "distanceUnits":"mi",
    "embedUrls":[],
    "httpsOnly":true,
    "isActive":true,
    "isUpgradeDisabled":false,
    "allowSpeedtestUrls":false,
    "passwordProtected":false,
    "themeColors":{
      "backgroundColor":"#ffffff",
      "primaryColor":"#ad1c07"
    },
    "serverIcon":"server",
    "speedLabel":"Mbps",
    "defaultMaxSpeed":"100",
    "testTypes":["ping","jitter","download","upload"],
    "isPaid":false,
    "isEUCountry":false
  },
  "config":{
    "rootDomain":"speedtestcustom.com",
    "logoCdnUrl":"https:\u002F\u002Flogos.speedtestcustom.com\u002Fprod\u002F",
    "countriesWithVat":["AT","BE","BG","HR","CY","CZ","DK","EE","FI","FR","DE","GR","HU","IE","IT","LV","LT","LU","MT","NL","PL","PT","RO","SK","SI","ES","SE","GB"],
    "premiumSubscriptionBasePrice":1995,
    "premiumSubscriptionServerPrice":995,
    "auth0":{
      "domain":"ookla.auth0.com",
      "clientId":"qZ22rLQ3HmY102QN05DIQGqFkz3AHdFr",
      "loginRedirectUrl":"https:\u002F\u002Faccount.speedtestcustom.com",
      "logoutRedirectUrl":"https:\u002F\u002Faccount.speedtestcustom.com\u002Flogin",
      "forgotPasswordLink":"https:\u002F\u002Faccount.speedtestcustom.com\u002Freset-password",
      "authorization":{
        "audience":"https:\u002F\u002Fapi.st-connect.com"
      },
      "management":{
        "connection":"OOKLA-AUTH"
      }
    },
    "privacyPolicyUpdated":"2018-05-18"
  },
  "testReport":{
    "ispName":"Triolan",
    "serverSponsor":"Kharkiv OnLine",
    "serverName":"Kharkiv",
    "serverId":2970,
    "jitter":1,
    "latency":2,
    "upload":11127625,
    "download":9591625,
    "guid":"be33e580-35e0-11ea-b23d-e75082e8c77d",
    "resultDate":"2020-01-13T08:43:51.000Z"
  },
  "serverList":[
    {
      "url":"http:\u002F\u002Fkharkiv.speedtest.triolan.com.ua:8080\u002Fspeedtest\u002Fupload.php",
      "lat":"50.0000",
      "lon":"36.2500",
      "distance":2,
      "name":"Kharkiv",
      "country":"Ukraine",
      "cc":"UA",
      "sponsor":"Triolan",
      "id":"1732",
      "preferred":0,
      "https_functional":1,
      "host":"kharkiv.speedtest.triolan.com.ua.prod.hosts.ooklaserver.net:8080",
      "force_ping_select":1
    },
    {
      "url":"http:\u002F\u002Fspeedtest.isp.kh.ua:8080\u002Fspeedtest\u002Fupload.php",
      "lat":"50.0000",
      "lon":"36.2500",
      "distance":2,
      "name":"Kharkiv",
      "country":"Ukraine",
      "cc":"UA",
      "sponsor":"Kharkiv OnLine",
      "id":"2970",
      "preferred":0,
      "https_functional":1,
      "host":"speedtest.isp.kh.ua:8080"
    },
    {
      "url":"http:\u002F\u002Fspeedtest.maxnet.ua:8080\u002Fspeedtest\u002Fupload.php",
      "lat":"50.0000",
      "lon":"36.2500",
      "distance":2,
      "name":"Kharkiv",
      "country":"Ukraine",
      "cc":"UA",
      "sponsor":"Maxnet LLC",
      "id":"20285",
      "preferred":0,
      "https_functional":1,
      "host":"speedtest.maxnet.ua.prod.hosts.ooklaserver.net:8080"
    },
    {
      "url":"http:\u002F\u002Fst7.utelecom.com.ua:8080\u002Fspeedtest\u002Fupload.php",
      "lat":"50.0000",
      "lon":"36.2500",
      "distance":2,
      "name":"Kharkiv",
      "country":"Ukraine",
      "cc":"UA",
      "sponsor":"PROSTO",
      "id":"10380",
      "preferred":0,
      "https_functional":1,
      "host":"st7.utelecom.com.ua.prod.hosts.ooklaserver.net:8080"
    },
    {
      "url":"http:\u002F\u002Fkharkovspeedtest.vodafone.ua:8080\u002Fspeedtest\u002Fupload.php",
      "lat":"50.0000",
      "lon":"36.2500",
      "distance":2,
      "name":"Kharkiv",
      "country":"Ukraine",
      "cc":"UA",
      "sponsor":"VF Ukraine Kharkiv",
      "id":"21662",
      "preferred":0,
      "https_functional":1,
      "host":"kharkovspeedtest.vodafone.ua:8080"
    },
    {
      "url":"http:\u002F\u002Fspeedtest.vega.com.ua:8080\u002Fspeedtest\u002Fupload.php",
      "lat":"50.0000",
      "lon":"36.2500",
      "distance":2,
      "name":"Kharkiv",
      "country":"Ukraine",
      "cc":"UA",
      "sponsor":"VEGA Kharkiv",
      "id":"21332",
      "preferred":0,
      "https_functional":1,
      "host":"speedtest.vega.com.ua:8080"
    },
    {
      "url":"http:\u002F\u002Fcheckspeed.skyline.kh.ua:8080\u002Fspeedtest\u002Fupload.php",
      "lat":"50.0000",
      "lon":"36.2500",
      "distance":2,
      "name":"Kharkiv",
      "country":"Ukraine",
      "cc":"UA",
      "sponsor":"ISP Skyline",
      "id":"30068",
      "preferred":0,
      "https_functional":1,
      "host":"checkspeed.skyline.kh.ua.prod.hosts.ooklaserver.net:8080"
    },
    {
      "url":"http:\u002F\u002Fsrv01-okl-kha.kyivstar.ua:8080\u002Fspeedtest\u002Fupload.php",
      "lat":"50.0000",
      "lon":"36.2500",
      "distance":2,
      "name":"Kharkiv",
      "country":"Ukraine",
      "cc":"UA",
      "sponsor":"Kyivstar",
      "id":"29488",
      "preferred":0,
      "https_functional":1,
      "host":"srv01-okl-kha.kyivstar.ua:8080"
    },
    {
      "url":"http:\u002F\u002Fbelgorod.speedtest.rt.ru:8080\u002Fspeedtest\u002Fupload.php",
      "lat":"50.6000",
      "lon":"36.6000",
      "distance":44,
      "name":"Belgorod",
      "country":"Russian Federation",
      "cc":"RU",
      "sponsor":"Rostelecom",
      "id":"3260",
      "preferred":0,
      "https_functional":1,
      "host":"belgorod.speedtest.rt.ru.prod.hosts.ooklaserver.net:8080"
    },
    {
      "url":"http:\u002F\u002Fspeedtest1.rutvn.ru:8080\u002Fspeedtest\u002Fupload.php",
      "lat":"50.6000",
      "lon":"36.6000",
      "distance":44,
      "name":"Belgorod",
      "country":"Russian Federation",
      "cc":"RU",
      "sponsor":"RusichTVN",
      "id":"4603",
      "preferred":0,
      "https_functional":1,
      "host":"speedtest1.rutvn.ru.prod.hosts.ooklaserver.net:8080"
    }
  ],
  "testGlobals":{
    "ipAddress":"185.38.217.69",
    "ispName":"Triolan",
    "ispId":102563,
    "location":{
      "latitude":49.982,
      "longitude":36.2566,
      "cityName":"Kharkiv",
      "countryCode":"UA",
      "countryName":"Ukraine",
      "regionCode":"63",
      "regionName":"Kharkivs'ka Oblast'"
    }
  },
  "performanceConfig":false,
  "logging":{
    "jwtToken":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImJjZTFkN2EwLWM3M2EtNGYyNC1hOGQ1LTBkYzhlZjIzNzAxOCIsInR5cGUiOiJoZWFkZXIifQ.Hhpu5EvEL09_akf8E_wjagZo4zsQXdgojyGXlLGzh4c",
    "buildId":1576175421006,
    "level":"info"
  },
  "engine":{
  }
}
